apiVersion: v1
kind: Service
metadata:
  name: gradio-service
  labels:
    app: gradio
spec:
  type: NodePort
  selector:
    app: gradio
  ports:
  - port: 7860
    targetPort: 7860
    protocol: TCP
    name: http
    nodePort: 30080
